### ISSUE TITLE
Thanks for the contribution, If can provide more test cases, or explain the documentation is best

### ISSUE THREAD

**Issue by xinghui-hou** [chaosblade-io/chaosblade-operator#1]
###  By example, I tested the cpu data，The load has increased to 80% in a short time.

![image](https://user-images.githubusercontent.com/10824788/68264338-7ad95280-0083-11ea-88af-82a6e6dacf3e.png)

**Comment by xcaspar** [comment]
@xinghui-hou Thank you for your interest in chaosblade, our focus this month is on documents.

**Comment by xcaspar** [comment]
https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s
