### ISSUE TITLE
create example Experiment failed

### ISSUE THREAD

**Issue by Cplo** [chaosblade-io/chaosblade-operator#11]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I failed to use the v0.5.0 version (successful installation)
kubectl create -f examples/delete_pod_by_names.yaml
operator error log:
`{"level":"error","ts":1581339227.346481,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"chaosblade-controller","request":"/delete-pod-by-names","error":"ChaosBlade.chaosblade.io \"delete-pod-by-names\" is invalid: []: Invalid value: map[string]interface {}{\"metadata\":map[string]interface {}{\"uid\":\"5984c9d7-4c04-11ea-bcc4-e236618161ec\", \"resourceVersion\":\"11617995800\", \"namespace\":\"\", \"clusterName\":\"\", \"selfLink\":\"/apis/chaosblade.io/v1alpha1/chaosblades/delete-pod-by-names\", \"creationTimestamp\":\"2020-02-10T12:53:35Z\", \"finalizers\":[]interface {}{\"finalizer.chaosblade.io\"}, \"name\":\"delete-pod-by-names\", \"generation\":1}, \"spec\":map[string]interface {}{\"experiments\":[]interface {}{map[string]interface {}{\"scope\":\"pod\", \"target\":\"pod\", \"action\":\"delete\", \"desc\":\"delete pod by names\", \"matchers\":[]interface {}{map[string]interface {}{\"value\":[]interface {}{\"ubuntu-68765bfb7c-nx4pr\"}, \"name\":\"names\"}, map[string]interface {}{\"name\":\"namespace\", \"value\":[]interface {}{\"default\"}}}}}}, \"status\":map[string]interface {}{\"expStatuses\":interface {}(nil)}, \"kind\":\"ChaosBlade\", \"apiVersion\":\"chaosblade.io/v1alpha1\"}: validation failure list:\nstatus.expStatuses in body must be of type array: \"null\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817221809-bf4de9df677c/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817221809-bf4de9df677c/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/Shared/ChaosBladeProjects/chaosblade-opensource/chaosblade-operator/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817221809-bf4de9df677c/pkg/util/wait/wait.go:88"}`

### How to reproduce it (as minimally and precisely as possible)

1. yaml install 
2. kubectl create -f examples/delete_pod_by_names.yaml 
3. log error

### Tell us your environment
I'm using k8s 1.10.5

**Comment by Cplo** [comment]
Update, another high version of k8s cluster（k8s 1.12） can work normally. So can you add the supported k8s version in the doc?

**Comment by jianxingzhe** [comment]
> Update, another high version of k8s cluster（k8s 1.12） can work normally. So can you add the supported k8s version in the doc?

https://github.com/kubernetes/kubernetes/blob/release-1.10/pkg/features/kube_features.go#L336

the `CustomResourceSubresources` feature is alpha in v1.10 and to enable it you need to set the CustomResourceSubresources feature gate on the kube-apiserver:
```
--feature-gates=CustomResourceSubresources=true
```
@xcaspar we should add the supported k8s version in the doc.

**Comment by Cplo** [comment]
get it, tks!

**Comment by xcaspar** [comment]
@Cplo @jianxingzhe I have added the content in the [README](https://github.com/chaosblade-io/chaosblade-operator#install-and-uninstall).
