### ISSUE TITLE
can not make build_all

### ISSUE THREAD

**Issue by NigelWu95** [chaosblade-io/chaosblade-operator#111]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

FATA[0000] unknown command "build" for "operator-sdk"

### Describe what you expected to happen

run operator-sdk help to get usage, no subcommand named build, but in Makefile use operator-sdk build in build_all task.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
`build_all` target contains chaosblade-operator tool and image compilation, requires operator-sdk command(0.19.x version).
