### ISSUE TITLE
1.4版本做实验失败

### ISSUE THREAD

**Issue by linkingli** [chaosblade-io/chaosblade-operator#128]
安装1.4版本，开始实验，没有权限
![image](https://user-images.githubusercontent.com/28832157/147206488-7d2eea82-c015-47ee-8d9e-84419d16f81c.png)

**Comment by linkingli** [comment]
可以在oprator中加上权限配置嘛？

**Comment by cadabrum** [comment]
Not sure if the problem is related with permissions, but this experiment definitely not works as expected if container is based on the minimal linux distro, with net-tools missing and so on. What are tht exact requirements to container enviroment to be able to run this experiment?

**Comment by linkingli** [comment]
i'd like to close
