### ISSUE TITLE
问题：安装chaosblade-operator1.5.0版本后 pod起不来

### ISSUE THREAD

**Issue by HQW640380** [chaosblade-io/chaosblade-operator#155]
## Issue Description
安装1.5.0版本后 看没有任何资源
#k get po -n chaosblade  出现以下提示
![image](https://user-images.githubusercontent.com/107013725/174810697-a0385928-98b6-47ab-838a-876a87cddd89.png)

No resources found in chaosblade namespace.
 #k get deployment -n chaosblade  后
![image](https://user-images.githubusercontent.com/107013725/174810819-aa769bb7-a677-49c5-9342-9046d55e756d.png)

NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
chaosblade-operator   0/1     0            0           4h24m
guestbook             0/2     0            0           37m
redis-master          0/1     0            0           37m
redis-slave           0/2     0            0           37m
#k describe deployment chaosblade-operator -n chaosblade 后
Name:                   chaosblade-operator
Namespace:              chaosblade
CreationTimestamp:      Tue, 21 Jun 2022 16:57:35 +0800
Labels:                 app.kubernetes.io/managed-by=Helm
Annotations:            meta.helm.sh/release-name: chaosblade-operator
                        meta.helm.sh/release-namespace: chaosblade
Selector:               name=chaosblade-operator
Replicas:               1 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           name=chaosblade-operator
                    part-of=chaosblade
  Service Account:  chaosblade
  Containers:
   chaosblade-operator:
    Image:      chaosbladeio/chaosblade-operator:1.5.0
    Port:       9443/TCP
    Host Port:  0/TCP
    Command:
      chaosblade-operator
    Args:
      --chaosblade-image-repository=chaosbladeio/chaosblade-tool
      --chaosblade-version=1.5.0
      --chaosblade-image-pull-policy=IfNotPresent
      --log-level=info
      --webhook-enable
      --daemonset-enable
      --remove-blade-interval=72h
      --chaosblade-namespace=chaosblade
    Environment:
      WATCH_NAMESPACE:
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    chaosblade-operator
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  chaosblade-webhook-server-cert
    Optional:    false
OldReplicaSets:  <none>
NewReplicaSet:   <none>
Events:          <none>

### How to reproduce it (as minimally and precisely as possible)
)

1. 
2. 
3.

**Comment by MandssS** [comment]
麻烦执行kubectl get pods -n chaosblade，看下pod的状态是啥情况，是否有具体报错
