### ISSUE TITLE
blade create k8s container-cpu error

### ISSUE THREAD

**Issue by Christophernt** [chaosblade-io/chaosblade-operator#160]
## Issue Description

*bug report*
### Describe what happened (or what feature you want)

time="2022-07-01T01:18:54Z" level=error msg="Invoke exec command error" command="[/apprun/chaosblade/blade create cri cpu fullload  --cpu-percent=85 --cgroup-root=/host-sys/fs/cgroup --container-id 852cff17999c --container-runtime docker]" container=chaosblade-tool err= error="command terminated with exit code 127" out= podName=chaosblade-tool-92789 podNamespace=chaosblade
time="2022-07-01T01:18:54Z" level=error msg="`pods/exec`: k8s exec failed, err: command terminated with exit code 127" location=github.com/chaosblade-io/chaosblade-operator/exec/model.execCommands.func1 uid=
time="2022-07-01T01:18:54Z" level=info msg="success: false, statuses: [{Id: State:Error Code:63061 Error:`pods/exec`: k8s exec failed, err: command terminated with exit code 127 Success:false Kind:container Identifier:chaosblade/cs-service-040/chaosblade-tool-92789/chaosblade-tool/852cff17999c/docker}]" experiment=e487577b4b93fa05

### Describe what you expected to happen

{"code":200,"success":true,"result":"xxxxxxxx"}

### How to reproduce it (as minimally and precisely as possible)

1. git clone -b v1.6.0 https://github.com/chaosblade-io/chaosblade-operator.git
2. /opt is modified to /apprun in codes
3. make build_all
4. docker tag chaosblade-operator:1.6.0 172.17.0.59:5000/chaosblade-operator:1.6.0
5. docker push 172.17.0.59:5000/chaosblade-operator:1.6.0
6. helm install agent chaos.tgz --namespace chaosblade --set env.name=default,license=206257cc2bb344629d333c9aae802e24,images.chaos.repository=172.17.0.59:5000/chaos-agent,images.chaos.version=1.0.0,transport.endpoint=172.17.0.59:7001,controller.cluster_id=1,controller.cluster_name=cluster1
7. ./blade create k8s container-cpu fullload --cpu-percent 85 --container-ids 852cff17999c --names chaosblade-tool-92789 --namespace chaosblade --kubeconfig ~/.kube/config

### Tell us your environment

docker 20.10.17
k8s 1.23.8
go 1.18.3
Linux version 3.10.0-1160.25.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Apr 28 21:49:45 UTC 2021

**Comment by MandssS** [comment]
please use master.  Check if the problem still exists

**Comment by Christophernt** [comment]
> please use master. Check if the problem still exists

The problem remains

**Comment by MandssS** [comment]
please exec `kubectl logs operator-name -n chaosblade` . View specific error reasons

**Comment by Christophernt** [comment]
> please exec `kubectl logs operator-name -n chaosblade` . View specific error reasons

![1657788839751](https://user-images.githubusercontent.com/24423772/178943828-4e8f12e0-7788-497d-abcc-1633ee91eae5.png)

**Comment by Christophernt** [comment]
solved
