### ISSUE TITLE
k8s 环境 chaosblade-box-agent 上报心跳到 chaosblade-box 存在 ip参数丢失

### ISSUE THREAD

**Issue by crushCoin** [chaosblade-io/chaosblade-operator#163]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
k8s 环境 chaosblade-box-agent 上报心跳到 chaosblade-box 存在 ip参数丢失 问题，导致 t_chaos_device 表 public_ip为空，chaosblade-box 界面 k8s 实验无法进行

### Describe what you expected to happen
心跳参数 ip有值

### How to reproduce it (as minimally and precisely as possible)

1.  helm 安装  chaosblade-box-1.0.1.tgz 、 chaosblade-box-agent-1.0.0.tgz
2. 
3. 

### Tell us your environment
k8s 1.20.0
chaosblade-box-1.0.1.tgz chaosblade-box-agent-1.0.0.tgz

### chaosblade-box 日志信息
![lALPJwKtz-qfch7M8M0HcA_1904_240](https://user-images.githubusercontent.com/15995863/179147828-5a7cb549-7c8a-4b90-ad38-46c1bf25ab1d.png)

### Anything else we need to know?
no

**Comment by MandssS** [comment]
麻烦执行下 `kubctl get services -n chaosblade` 查看下agent的service是否还在正常运行

**Comment by crushCoin** [comment]
> 麻烦执行下 `kubctl get services -n chaosblade` 查看下agent的service是否还在正常运行

![企业微信截图_16578683896581](https://user-images.githubusercontent.com/15995863/179169417-c09f342d-3059-411c-9a43-68972ba04c9b.png)
![企业微信截图_16578684138417](https://user-images.githubusercontent.com/15995863/179169497-d985d4e4-d6b4-4c28-897e-af983bd2f417.png)

**Comment by crushCoin** [comment]
https://github.com/chaosblade-io/chaosblade-box-agent/blob/main/collector/kubernetes/pod.go#L334
![企业微信截图_16578786294355](https://user-images.githubusercontent.com/15995863/179199553-fd1de77f-a572-42fd-b140-1b53ecc20f4e.png)
chaosblade-box-agent 中 service  不是 loadBalancer 类型 情况下：
chaosblade-box-agent   命令参数  kubernetes.pod.report=true 改为 kubernetes.pod.report=false
或者
chaosblade-box-agent 中 service  name 只要不是 chaos-agent 都可以
