### ISSUE TITLE
chaoblade operator 1.6.0版本 container cpu 无法销毁实验

### ISSUE THREAD

**Issue by w2481296** [chaosblade-io/chaosblade-operator#165]
## Issue Description

Type: bug report

apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: test
spec:
  experiments:
  - action: fullload
    matchers:
    - name: namespace
      value:
      - default
    - name: names
      value:
      - ssd-6fdf679d89-dgc96
    - name: container-names
      value:
      - ssd
    - name: cpu-percent
      value:
      - "50"
    scope: container
    target: cpu

使用上述文件创建之后，无法销毁实现，状态是Destroying

-o json的内容是 
  expStatuses:
  - action: fullload
    error: see resStatus for the error details
    resStatuses:
    - error: invalid parameter `container-id`, can not find container by id
      id: a0eaf77eddc70487
      identifier: default/host-172-18-199-29/ssd-6fdf679d89-dgc96/ssd/f6f6aa964a60/docker
      kind: container
      state: Error
      success: false

说不能通过id找到容器，我给容器注入cpu满载测试 container-id这个参数是必须的吗，我是用的容器名字这样不可以吗？
### Describe what you expected to happen
应该根据id或者名字都可以注入和销毁实验

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
k8s 1.17.8
operator 1.6

**Comment by MandssS** [comment]
hi，请用最新的1.6.1版本进行测试，该问题已修复 https://github.com/chaosblade-io/chaosblade-operator/commit/d751377f0b86123837422ad42940dfca0ed0a2ee
