### ISSUE TITLE
error: blade command not found

### ISSUE THREAD

**Issue by beiketianzhuang** [chaosblade-io/chaosblade-operator#169]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
`./blade create k8s container-mem load --mode ram --mem-percent 50 --timeout 400 --names spinach-cqqeqmxd-5bb565597d-zlfnt --container-names spinach-cqqeqmxd --kubeconfig /data/project/chaosblade/config  --namespace spinach -d
{"code":54000,"success":false,"error":"unexpected status, expected status: `create`, but the real status: `Error`, please wait!","result":{"uid":"c1dfdf87b77033f6","success":false,"error":"`pods/exec`: k8s exec failed, err: Internal error occurred: error executing command in container: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"57402692a93a104ce068280cca4462366b9349988644dbca349d2be18bb84645\": OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"/opt/chaosblade/blade\": stat /opt/chaosblade/blade: no such file or directory: unknown","statuses":[{"state":"Error","error":"`pods/exec`: k8s exec failed, err: Internal error occurred: error executing command in container: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec \"57402692a93a104ce068280cca4462366b9349988644dbca349d2be18bb84645\": OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"/opt/chaosblade/blade\": stat /opt/chaosblade/blade: no such file or directory: unknown","success":false,"kind":"container","identifier":"spinach/eklet-subnet-im3wpegh/spinach-cqqeqmxd-5bb565597d-zlfnt/spinach-cqqeqmxd/f12f8f8660453e1534256cb755f9b16c66c4ed4ac050b2e609c4ad52159ab3be/containerd"}]}}`

#### I want to perform k8s fault injection
`./blade create k8s container-mem load --mode ram --mem-percent 50 --timeout 400 --names spinach-cqqeqmxd-5bb565597d-zlfnt --container-names spinach-cqqeqmxd --kubeconfig /data/project/chaosblade/config  --namespace spinach -d`

### How to reproduce it (as minimally and precisely as possible)

1. download chaosblade-operator-1.6.0.tgz
2. kubectl create namespace chaosblade
3. helm install chaosblade-operator chaosblade-operator-1.6.0.tgz --namespace chaosblade
4. Use kubectl get pods  -n chaosblade to check the installation status of the Pod. If both are running, the installation was successful
5. ./blade create k8s container-mem load --mode ram --mem-percent 50 --timeout 400 --names spinach-cqqeqmxd-5bb565597d-zlfnt --container-names spinach-cqqeqmxd --kubeconfig /data/project/chaosblade/config  --namespace spinach -d

### Tell us your environment
kubernetes: v1.18.4
containerd: v1.3+
chaosblade client: v1.6.1

**Comment by beiketianzhuang** [comment]
@xcaspar

**Comment by Icesource** [comment]
@beiketianzhuang  I can't reproduce your problem after testing. Please use `kubectl get pods -n chaosblade` to confirm that chaosblade-operator is correctly installed in your k8s cluster.  The correct return value is
```
chaosblade-operator-ccc75ffc5-5fjdp   1/1     Running   0          2m31s
chaosblade-tool-5xh85                 1/1     Running   0          2m31s
chaosblade-tool-ndqx7                 1/1     Running   0          2m31s
```

An make sure the kubeconfig file in the blade command points to your k8s cluster

**Comment by beiketianzhuang** [comment]
> @beiketianzhuang I can't reproduce your problem after testing. Please use `kubectl get pods -n chaosblade` to confirm that chaosblade-operator is correctly installed in your k8s cluster. The correct return value is
> 
> ```
> chaosblade-operator-ccc75ffc5-5fjdp   1/1     Running   0          2m31s
> chaosblade-tool-5xh85                 1/1     Running   0          2m31s
> chaosblade-tool-ndqx7                 1/1     Running   0          2m31s
> ```
> 
> An make sure the kubeconfig file in the blade command points to your k8s cluster

this is my return value. It seems to be fine

<img width="650" alt="image" src="https://user-images.githubusercontent.com/23691253/183604208-3aee6055-808c-44aa-aa90-7b07a131e999.png">

**Comment by beiketianzhuang** [comment]
> @beiketianzhuang I can't reproduce your problem after testing. Please use `kubectl get pods -n chaosblade` to confirm that chaosblade-operator is correctly installed in your k8s cluster. The correct return value is
> 
> ```
> chaosblade-operator-ccc75ffc5-5fjdp   1/1     Running   0          2m31s
> chaosblade-tool-5xh85                 1/1     Running   0          2m31s
> chaosblade-tool-ndqx7                 1/1     Running   0          2m31s
> ```
> 
> An make sure the kubeconfig file in the blade command points to your k8s cluster

operator logs
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/23691253/183606185-47eb9770-f77d-4000-a063-23888fbf4bda.png">

**Comment by Icesource** [comment]
Maybe you can uninstall and reinstall the operator to try to solve the problem.
```
kubectl delete crd chaosblades.chaosblade.io
helm uninstall chaosblade-operator -n chaosblade
```
