### ISSUE TITLE
helm部署chaosblade-operator后启动失败，CrashLoopBackOff状态

### ISSUE THREAD

**Issue by Jim-1011** [chaosblade-io/chaosblade-operator#175]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
通过helm v3部署chaosblade-operator后检查chaosblade-operator启动失败不是running
 helm install chaosblade-operator chaosblade-operator-1.4.0-v3-x86.tgz --namespace kube-system
W0826 11:57:54.926361 2613963 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 11:57:54.940917 2613963 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 11:57:56.946819 2613963 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 11:57:58.948079 2613963 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 11:58:00.948830 2613963 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0826 11:58:01.819827 2613963 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0826 11:58:01.825833 2613963 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0826 11:58:01.843757 2613963 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0826 11:58:01.883348 2613963 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0826 11:58:01.889688 2613963 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0826 11:58:01.931233 2613963 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
NAME: chaosblade-operator
LAST DEPLOYED: Fri Aug 26 11:58:01 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for using chaosblade.

 kubectl get pod -n kube-system
NAME                                         READY   STATUS                 RESTARTS   AGE
chaosblade-operator-55dbff6977-jnknp         0/1     CrashLoopBackOff       1          20s
chaosblade-tool-bj88c                        0/1     CreateContainerError   0          20s
chaosblade-tool-rtfgh                        0/1     CreateContainerError   0          18s

Args:
      --chaosblade-image-repository=/testservice/chaosblade-tool-x86
      --chaosblade-version=1.4.0
      --chaosblade-image-pull-policy=IfNotPresent
      --log-level=info
      --webhook-enable
      --daemonset-enable
      --remove-blade-interval=72h
      --chaosblade-namespace=kube-system
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:318: starting container process caused "exec: \"chaosblade-operator\": executable file not found in $PATH": unknown
      Exit Code:    127
      Started:      Fri, 26 Aug 2022 11:58:46 +0800
      Finished:     Fri, 26 Aug 2022 11:58:46 +0800

### Describe what you expected to happen

部署后应该是running才对
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MandssS** [comment]
将会在下一个版本中进行修复
