### ISSUE TITLE
对k8s的node进行cpu故障注入时，提示找不到node

### ISSUE THREAD

**Issue by leslie110** [chaosblade-io/chaosblade-operator#198]
![image](https://user-images.githubusercontent.com/33894471/207812172-57512492-3b80-4fcb-93f5-509d4f6611f8.png)
我的k8s集群各个节点如下：
![image](https://user-images.githubusercontent.com/33894471/207812358-897d11d4-2778-47d9-9516-41ed7971ef85.png)
该集群时使用rke进行安装

**Comment by MandssS** [comment]
Please use the latest version, it has been resolved
