### ISSUE TITLE
Error: ImagePullBackOff

### ISSUE THREAD

**Issue by 865428222** [chaosblade-io/chaosblade-operator#2]
chaosblade-operator/blob/master/deploy/oss/daemonset.yaml  
containers:  
      - image: registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator:0.4.0  
Failed to pull image "registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-operator:0.4.0": rpc error: code = Unknown desc = Error: image chaosblade/chaosblade-operator:0.4.0 not found

**Comment by xcaspar** [comment]
@865428222 The latest version of chaosblade-operator image is 0.0.1, please see https://github.com/chaosblade-io/chaosblade-operator/releases/tag/v0.0.1 for the details.
