### ISSUE TITLE
k8s how change --container-runtime

### ISSUE THREAD

**Issue by TidalPoo** [chaosblade-io/chaosblade-operator#201]
by default in blade-operator `--container-runtime docker`

when i use `blade c k8s pod-cpu`...

operator send error:

`level=info msg="get err message" command="[/opt/chaosblade/blade create cri cpu fullload  --cpu-percent=10 --container-id cri-o://faaf --container-runtime docker]" container=chaosblade-tool err="{\"code\":63067,\"success\":false,\"error\":\"`GetClient`: container exec failed, err: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\"}" out= podName=chaosblade-tool-tjh8m podNamespace=chaosblade`

`blade c k8s pod-cpu` don't have option -`-container-runtime`

**Comment by oncefalse** [comment]
碰到了同样的问题，我使用的chaosblade-operator 版本是1.5.1 
大佬能抽空看下这个问题吗 @tiny-x

**Comment by oncefalse** [comment]
已解决
我这边发现这个问题再1.7.0中已修复。
首先重声明下背景
在原先k8s 1.23 版本中 chaosblade-operator-1.5.1 都正常运行，然后k8s 升级到1.24后将容器化实现由Docker改成 containerd。
因此可以大体猜出这个报错原因是，chaosblade-operator底层调用实现的是Docker 的协议，然后由于k8s升级导致 Docker 找不到。那么修复方向就是修改 chaosblade-operator 调用的协议为 containerd
下面是经过扒源码得出，生成命令时会生成 cri 命令（cri 调用协议有containerd），而我们报错是因为都生成的是Docker命令。所以可以看出关键代码
```
containerObjectMetaList[0].ContainerRuntime == container.ContainerdRuntime
```
![image](https://github.com/chaosblade-io/chaosblade-operator/assets/96274070/32aa17eb-a7ce-4404-b9fc-29f0f623a779)

它会根据容器的元数据列表中的ContainerRuntime字段判断生成CRI 还是 Docker 命令。那么再去找下containerObjectMetaList[0].ContainerRuntime 哪里有赋值，会发现以下代码
1.7.0中有赋值
<img width="1054" alt="image" src="https://github.com/chaosblade-io/chaosblade-operator/assets/96274070/90a43db0-1b30-422c-9b1f-1b430788df29">
但是1.5.1中没有赋值
<img width="978" alt="image" src="https://github.com/chaosblade-io/chaosblade-operator/assets/96274070/c33cb2cf-2ae5-4308-b4cc-a03cc2dbb300">
以上ContainerRuntime 的代码同步1.7.0，运行之后发现了新问题。报错如下
找不到 container
![image](https://github.com/chaosblade-io/chaosblade-operator/assets/96274070/ee86bc58-bb5d-4757-b54d-217af19d4543)
再对比 1.7.0 中的代码发现有根据ContainerRuntime判断进行截断container_id 关键代码如下
<img width="968" alt="image" src="https://github.com/chaosblade-io/chaosblade-operator/assets/96274070/f8cf8cc8-795d-44d0-b5e7-e516630929a6">

**Comment by oncefalse** [comment]
> 已解决 我这边发现这个问题再1.7.0中已修复。 首先重声明下背景 在原先k8s 1.23 版本中 chaosblade-operator-1.5.1 都正常运行，然后k8s 升级到1.24后将容器化实现由Docker改成 containerd。 因此可以大体猜出这个报错原因是，chaosblade-operator底层调用实现的是Docker 的协议，然后由于k8s升级导致 Docker 找不到。那么修复方向就是修改 chaosblade-operator 调用的协议为 containerd 下面是经过扒源码得出，生成命令时会生成 cri 命令（cri 调用协议有containerd），而我们报错是因为都生成的是Docker命令。所以可以看出关键代码
> 
> ```
> containerObjectMetaList[0].ContainerRuntime == container.ContainerdRuntime
> ```
> 
> ![image](https://user-images.githubusercontent.com/96274070/247394404-32aa17eb-a7ce-4404-b9fc-29f0f623a779.png)
> 
> 它会根据容器的元数据列表中的ContainerRuntime字段判断生成CRI 还是 Docker 命令。那么再去找下containerObjectMetaList[0].ContainerRuntime 哪里有赋值，会发现以下代码 1.7.0中有赋值 <img alt="image" width="1054" src="https://user-images.githubusercontent.com/96274070/247393858-90a43db0-1b30-422c-9b1f-1b430788df29.png"> 但是1.5.1中没有赋值 <img alt="image" width="978" src="https://user-images.githubusercontent.com/96274070/247393920-c33cb2cf-2ae5-4308-b4cc-a03cc2dbb300.png"> 以上ContainerRuntime 的代码同步1.7.0，运行之后发现了新问题。报错如下 找不到 container ![image](https://user-images.githubusercontent.com/96274070/247394107-ee86bc58-bb5d-4757-b54d-217af19d4543.png) 再对比 1.7.0 中的代码发现有根据ContainerRuntime判断进行截断container_id 关键代码如下 <img alt="image" width="968" src="https://user-images.githubusercontent.com/96274070/247394244-f8cf8cc8-795d-44d0-b5e7-e516630929a6.png">

在我这边经过修改以上两部分的代码，得以修复了这个，希望能帮助到其它遇到相同问题的同学

**Comment by binbin0325** [comment]
你可以指定--container-runtime 参数（containerd，docker）
