### ISSUE TITLE
磁盘io以及fill使用yaml成功但无现象，使用1.5版本

### ISSUE THREAD

**Issue by RickDamon** [chaosblade-io/chaosblade-operator#209]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

![image](https://github.com/chaosblade-io/chaosblade-operator/assets/72897771/c19c0ff3-77d1-4365-bec9-259d4e0edee7)

### Describe what you expected to happen
./blade check os
有磁盘的报错，但是不清楚报错的原因
执行disk-burn以及diskfill的任务，没有现象，但是不报错

### Tell us your environment

![image](https://github.com/chaosblade-io/chaosblade-operator/assets/72897771/55e3e54f-279a-4ae2-871f-d6f3bbf4924a)
k8s集群环境，用yaml文件执行任务

**Comment by binbin0325** [comment]
升级最新版本
