### ISSUE TITLE
There is no 'ps' in the container, and the execution of the killing process experiment scenario fails

### ISSUE THREAD

**Issue by myamia** [chaosblade-io/chaosblade-operator#224]
![图片](https://github.com/chaosblade-io/chaosblade-operator/assets/52197393/605bf3b8-b78f-466c-b433-8c2659889207)

![图片](https://github.com/chaosblade-io/chaosblade-operator/assets/52197393/8005f88a-cad9-46dc-82ed-7e8926d987d1)

**Comment by binbin0325** [comment]
environmental problems, you can install ps
