### ISSUE TITLE
Can it deploy in other namespace,not deploy in kube-system?

### ISSUE THREAD

**Issue by lcwus2** [chaosblade-io/chaosblade-operator#3]
I use " helm install --namespace xxx --name chaosblade-operator chaosblade-operator-0.0.1.tgz" to deploy. Though I inputted another namespace, it still deployed in kube-system

**Comment by xcaspar** [comment]
@lcwus2 Modifications are not currently supported, but there are two ways to do this:
1. Unzip the helm package, modify all yaml files: change kube-system to your desired value.
2. Download all the yaml files from https://github.com/chaosblade-io/chaosblade-operator/tree/master/deploy/oss, change kube-system to your desired value, and execute these yaml files using kubectl command
