### ISSUE TITLE
没有chaosblade-operator-yaml-0.6.0版本

### ISSUE THREAD

**Issue by aioloszcy** [chaosblade-io/chaosblade-operator#32]
## Issue Description
kubectl安装小节里提示使用chaosblade-operator-yaml-VERSION的版本，但是在最新release里没有找到。
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tiny-x** [comment]
YAML installation is no longer provided, use Helm
