### ISSUE TITLE
Error "can not find the scope controller for creating"

### ISSUE THREAD

**Issue by baiyanquan** [chaosblade-io/chaosblade-operator#46]
## Issue Description

_bug report_

### Describe what happened (or what feature you want)

I'd like to run node-cpu-load experiment, but it returned error "can not find the scope controller for creating".

### How to reproduce it (as minimally and precisely as possible)

1. Retype the command "blade create k8s node-cpu fullload --names 192.168.199.32 --cpu-percent 80 --kubeconfig ~/.kube/config"
2. 
3. 

### Tell us your environment

Kubernetes: v1.13.5(installed by kubeasz)

Node configuration: 
| NAME | STATUS | ROLES |
| ---- | ------ | ----- |
| 192.168.199.31 | Ready,SchedulingDisabled | node |
| 192.168.199.32 | Ready | node |
| 192.168.199.33 | Ready | node |
| 192.168.199.34 | Ready | node |
| 192.168.199.35 | Ready | node |

### Anything else we need to know?

All nodes in the environment have already configured ssh connection without password. Besides, I tried to use "--labels" instead of "--names" but it returns the same result. YAML has also been tried but failed. The return message is:
{"code":504,"success":false,"error":"unexpected status, the real value is Error","result":{"uid":"549d9830c459a3c8","success":false,"error":"unexpected status, the real value is Error","statuses":[{"state":"Error","kind":"","error":"can not find the scope controller for creating","success":false}]}}

Maybe I have made some mistakes during the test. Hope for your suggestions or tips.

**Comment by tiny-x** [comment]
see https://github.com/chaosblade-io/chaosblade-operator/issues/44

**Comment by baiyanquan** [comment]
> see #44

Sorry, but can you explain "Node experiment support SSH channels only" more clearly? I have already configured ssh connection without password among all nodes in Kubernetes. Is there any other configuration? Hope for your suggestions or tips, thank you.


![](https://github.com/baiyanquan/ImageRepository/blob/main/ChaobladeQA.png?raw=true)

**Comment by tiny-x** [comment]
without password use
`blade create k8s node-mem load --channel ssh --ssh-key /tmp/key.pem`

Version 0.8.0 has recover the Node daemonset experiment, install 0.8.0 you can use
`blade create k8s node-cpu fullload --names 192.168.199.32 --cpu-percent 80 --kubeconfig ~/.kube/config`
Welcome to use.

**Comment by douxiaoniu77** [comment]
Hi Tiny, 
I also ran into the similar issue with error "can not find the scope controller for creating"， for the version 0.8.0, do you refer to the chaosblase-operator of 0.8.0? 
You know, I didn't find the tgz file of operator from https://github.com/chaosblade-io/chaosblade-operator/releases，

**Comment by tiny-x** [comment]
@douxiaoniu77 
https://github.com/chaosblade-io/chaosblade/releases/tag/v0.8.0

**Comment by baiyanquan** [comment]
Thank you, Tiny. The problem has been solved in the version 0.8.0. Thanks for your help!
