### ISSUE TITLE
helm install failed

### ISSUE THREAD

**Issue by yanbowang1** [chaosblade-io/chaosblade-operator#86]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
 I used "helm install chaosblade-operator chaosblade-operator-1.2.0-v3.tgz --namespace kube-system" successfully at first, then I uninstalled it using "helm install chaosblade-operator chaosblade-operator-1.2.0-v3.tgz --namespace kube-system", and then re-used the method, but an error was reported.

### Describe what you expected to happen
Name:         chaosblade-operator-67779995db-xj8f7
Namespace:    kube-system
Priority:     0
Node:         k8snode2/192.168.124.132
Start Time:   Mon, 28 Jun 2021 17:44:36 +0800
Labels:       name=chaosblade-operator
              part-of=chaosblade
              pod-template-hash=67779995db
Annotations:  <none>
Status:       Running
IP:           10.244.2.2
IPs:
  IP:           10.244.2.2
Controlled By:  ReplicaSet/chaosblade-operator-67779995db
Containers:
  chaosblade-operator:
    Container ID:  docker://3ffe3251a7c6a54a8cea3b5fc007c68cd8761febdff1c7df94dff3e821602de2
    Image:         chaosbladeio/chaosblade-operator:1.2.0
    Image ID:      docker://sha256:c4dabdc683d400dcd6a5ca3a15544c3c9152feb9fe0db44a8cb9e940f68346c9
    Port:          9443/TCP
    Host Port:     0/TCP
    Command:
      chaosblade-operator
    Args:
      --chaosblade-image-repository=chaosbladeio/chaosblade-tool
      --chaosblade-version=1.2.0
      --chaosblade-image-pull-policy=IfNotPresent
      --log-level=info
      --webhook-enable
      --daemonset-enable
      --remove-blade-interval=72h
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 28 Jun 2021 17:45:21 +0800
      Finished:     Mon, 28 Jun 2021 17:45:22 +0800
    Ready:          False
    Restart Count:  3
    Environment:
      WATCH_NAMESPACE:  
      POD_NAME:         chaosblade-operator-67779995db-xj8f7 (v1:metadata.name)
      OPERATOR_NAME:    chaosblade-operator
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from chaosblade-token-gpssb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  chaosblade-webhook-server-cert
    Optional:    false
  chaosblade-token-gpssb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  chaosblade-token-gpssb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  87s                default-scheduler  Successfully assigned kube-system/chaosblade-operator-67779995db-xj8f7 to k8snode2
  Normal   Pulled     23h (x4 over 23h)  kubelet            Container image "chaosbladeio/chaosblade-operator:1.2.0" already present on machine
  Normal   Created    23h (x4 over 23h)  kubelet            Created container chaosblade-operator
  Normal   Started    23h (x4 over 23h)  kubelet            Started container chaosblade-operator
  Warning  BackOff    23h (x8 over 23h)  kubelet            Back-off restarting failed container

### How to reproduce it (as minimally and precisely as possible)

1.helm install chaosblade-operator chaosblade-operator-1.2.0-v3.tgz --namespace kube-system

**Comment by xcaspar** [comment]
Please use `kubectl log` command to see the detail of error.

**Comment by yanbowang1** [comment]
My firewall port is not open. After opening the port, the problem is solved
