### ISSUE TITLE
Node/Pod Network Loss/Latency Experiment Questions

### ISSUE THREAD

**Issue by ijt32031** [chaosblade-io/chaosblade-operator#93]
I had the following questions: 
1. Does "local-port" need to be defined in the context of _node_ network latency?  Can you give an example of how would work (e.g. would it be the NodePort for a service? Port 6443 in the case of the kube-api-server?) 
2. What does the "offset" config do for pod network delay? 

Thanks!

**Comment by xcaspar** [comment]
Please use `-h` flag to see the usage details.
